// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iywawnkoepstnavuifyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5d2F3bmtvZXBzdG5hdnVpZnlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2ODA4NDgsImV4cCI6MjA2MjI1Njg0OH0.URMzyAbvcp_z8dimJu37H4z9t-LiMS_sTIi_yzg6xF0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);